/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;
import demo.Library;

public class App {
    public String getGreeting() {
        return "Hello world from app. " + new Library().someLibraryMethod();
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
